name: Run check: Build image

on:
  pull_request:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ github.repository }}:${{ env.GITHUB_SHA_SHORT }}